FROM apache/superset:superset_version

# Set the working directory
WORKDIR /app

USER root

RUN apt update; apt install gcc gpp -y

RUN apt-get update && apt-get install -y \
    pkg-config \
    libmariadb-dev \
    python3-dev \
    build-essential

COPY requirements.txt /tmp/requirements.txt

RUN uv pip install -r /tmp/requirements.txt

RUN uv pip install -r /app/superset/translations/requirements.txt

#RUN mkdir -p /app/superset/translations/pt_BR/LC_MESSAGES && \
#    curl -L \
#    https://raw.githubusercontent.com/apache/superset/refs/heads/6.0/superset/translations/pt_BR/LC_MESSAGES/messages.po \
#    -o /app/superset/translations/pt_BR/LC_MESSAGES/messages.po

#RUN pybabel compile -d /app/superset/translations \
#    && po2json /app/superset/translations/pt_BR/LC_MESSAGES/messages.po \
#       /app/superset/translations/pt_BR/LC_MESSAGES/messages.json \
#       --domain superset     --ignore-obsolete \
#       --format jed1.x

USER superset
