FROM apache/superset:superset_version

# Set the working directory
WORKDIR /app

USER root

RUN apt update; apt install gcc gpp -y

RUN apt-get update && apt-get install -y \
    pkg-config \
    libmariadb-dev \
    python3-dev \
    build-essential

COPY default/requirements.txt /tmp/requirements.txt

COPY default/translations/pt_br-superset_version.po /app/superset/translations/pt_BR/LC_MESSAGES/messages.po

RUN uv pip install -r /tmp/requirements.txt

RUN uv pip install -r /app/superset/translations/requirements.txt

RUN pybabel compile -d /app/superset/translations \
    && po2json /app/superset/translations/pt_BR/LC_MESSAGES/messages.po \
       /app/superset/translations/pt_BR/LC_MESSAGES/messages.json \
       --domain superset     --ignore-obsolete \
       --format jed1.x

USER superset
